title: "Tycho van Zunderd"
author: "Tycho van Zunderd"
description: "Software Engineer @ Kropman"
baseurl: "" # Leave empty for GitHub Pages
url: "https://tyfcho.github.io"
github_username: "Tyfcho"
theme: minima
